---
basedir: '/opt'
driver_dir: '/opt/emmgr/driver'
etcdir: '/etc/emmgr'

domain: 'example.com'

em:
  default_configfile_server: 'tftp://10.0.0.1'
  default_firmware_server: 'tftp://10.0.0.2'
  scriptaccount:
    username: '<username>'
    password: '<secret password>'
    enable_password: '<secret enable password>'
    use_ssh: true
