site_name: Emmgr documentatgion
site_dir: ../app/static/docs
use_directory_urls: false
theme: 'material'
pages:
  - Home: index.md
  - API: api.md
  - Development: devel.md

markdown_extensions:
    - toc:
        permalink: True
    - tables:
